### ISSUE TITLE
local.css: Tolino readers display whole book in italics

### ISSUE THREAD

**Issue by Moonbase59** [standardebooks/e-w-hornung_the-black-mask#1]
Tolino readers (like my Tolino Vision 5, firmware 14.2.0) display _the whole book in italics_, which is awkward to read. These apparently don’t recognize the `body [xml|lang]{ … }` correctly and thus use the specified `font-style: italic;` throughout the book.

https://github.com/standardebooks/e-w-hornung_the-black-mask/blob/057c7a8be5cf667b219b3a6fded159fc80a46be1/src/epub/css/local.css#L5-L7

I could remedy the problem by commenting out the above. It now looks beautiful on the Tolino again, like its series predecessor, E. W. Hornung’s »The Amateur Cracksman«.

I’d much appreciate if this could be changed, please.

---

After some more investigation, I think the intended outcome (italicize foreign-language text) could be achieved by replacing above against:

```css
body [lang]{
	font-style: italic;
}
```
because—fortunately—all declarations in the book carry _both_ `xml:lang` _and_ `lang` attributes. This change works on the Tolino.

**Comment by acabal** [comment]
This is fixed in 5b54815, but since this will only go live in the next toolset release, it will be some time before the corpus is updated. Thanks for spotting it!

**Comment by Moonbase59** [comment]
And thanks to you for the quick answer! :-)
