### ISSUE TITLE
Song/verse double-spacing on Tolino devices (<br/> not suppressed)

### ISSUE THREAD

**Issue by Moonbase59** [standardebooks/e-w-hornung_the-black-mask#2]
Seems Tolino readers use a rather old rendering engine. The song at the beginning of chapter 3 (»The Fate of Faustina«) is displayed double-spaced, apparently because of the `display: block` declaration and the suppression of `<br/>` not being honored by the Tolino:

https://github.com/standardebooks/e-w-hornung_the-black-mask/blob/057c7a8be5cf667b219b3a6fded159fc80a46be1/src/epub/css/local.css#L26-L29

![screenshot_20211116_104535](https://user-images.githubusercontent.com/3706922/141961928-2a83f1c4-e1c6-4dee-80e8-9ed7fe055443.png)

I’m using a Tolino Vision 5, firmware 14.2.0.

It _does_ display correctly in Calibre’s eBook reader (v5.32, Linux), though:

![The Black Mask  EPUB  — eBook-Betrachter_001](https://user-images.githubusercontent.com/3706922/141964340-7246b835-7944-4de8-b0ec-b3ebafae8e5c.png)

**Comment by acabal** [comment]
I don't think we're going to be able to fix this. The Tolino renderer is apparently very bad. I would guess it's based on a very old version of ADE. Sorry!
